import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";

export async function POST(req: Request) {
  try {
    const data = await req.json();

    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(234, 88, 12);
    doc.text("StockSense AI Report", margin, y);

    y += 12;
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`Product: ${data.productName || "Unknown"}`, margin, y);

    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date(data.analyzedAt || new Date()).toLocaleString()}`, margin, y);

    // Divider line
    y += 8;
    doc.setDrawColor(234, 88, 12);
    doc.line(margin, y, 190, y);

    // Analysis Summary
    y += 12;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Analysis Summary", margin, y);

    y += 8;
    doc.setFontSize(11);
    doc.text(`Sentiment:`, margin, y);
    doc.setTextColor(data.sentiment_score > 0.5 ? 22 : data.sentiment_score < 0 ? 220 : 100, 100, 100);
    doc.text(`${data.sentiment_label || "N/A"} (${(data.sentiment_score || 0).toFixed(2)})`, margin + 30, y);
    doc.setTextColor(0, 0, 0);
    doc.text(`Demand Forecast:`, margin + 90, y);
    doc.text(`${data.demand || 0} units`, margin + 130, y);

    y += 7;
    doc.text(`Risk Level:`, margin, y);
    const riskColor = data.risk === "Critical" ? [220, 38, 38] : data.risk === "High" ? [234, 88, 12] : data.risk === "Medium" ? [202, 138, 4] : [22, 163, 74];
    doc.setTextColor(...(riskColor as [number, number, number]));
    doc.text(`${data.risk || "Low"}`, margin + 30, y);
    doc.setTextColor(0, 0, 0);
    doc.text(`Reorder Quantity:`, margin + 90, y);
    doc.text(`${data.reorder || 0} units`, margin + 130, y);

    y += 7;
    doc.text(`Confidence:`, margin, y);
    doc.text(`${((data.confidence || 0) * 100).toFixed(0)}%`, margin + 30, y);
    doc.text(`Stockout in:`, margin + 90, y);
    doc.text(`${data.stockout_days || 0} days (${data.stockout_date || "N/A"})`, margin + 120, y);

    // Key Insights
    y += 15;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, 190, y);
    y += 10;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Key Insights", margin, y);

    y += 8;
    doc.setFontSize(11);
    if (data.strengths?.length > 0) {
      doc.setTextColor(22, 163, 74);
      doc.text("Strengths:", margin, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
      for (const s of data.strengths) {
        const lines = doc.splitTextToSize(`\u2022 ${s}`, 165);
        doc.text(lines, margin + 3, y);
        y += lines.length * 6;
      }
    }

    if (data.issues?.length > 0) {
      y += 4;
      doc.setTextColor(220, 38, 38);
      doc.text("Issues:", margin, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
      for (const s of data.issues) {
        const lines = doc.splitTextToSize(`\u2022 ${s}`, 165);
        doc.text(lines, margin + 3, y);
        y += lines.length * 6;
      }
    }

    if (data.improvements?.length > 0) {
      y += 4;
      doc.setTextColor(37, 99, 235);
      doc.text("Improvements:", margin, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
      for (const s of data.improvements) {
        const lines = doc.splitTextToSize(`\u2022 ${s}`, 165);
        doc.text(lines, margin + 3, y);
        y += lines.length * 6;
      }
    }

    // Action Plan
    y += 10;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, 190, y);
    y += 10;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Action Plan", margin, y);

    y += 8;
    doc.setFontSize(11);
    const plan = data.restock_plan || "No specific restock plan generated.";
    const restockLines = doc.splitTextToSize(plan, 170);
    doc.text(restockLines, margin, y);
    y += restockLines.length * 6 + 6;

    const explanation = data.explanation || "No detailed explanation available.";
    const explanationLines = doc.splitTextToSize(explanation, 170);
    doc.text(explanationLines, margin, y);

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by StockSense AI — Intelligent Inventory Management", margin, pageHeight - 10);

    // Output as ArrayBuffer
    const pdfBytes = doc.output("arraybuffer");
    const safeName = (data.productName || "product").replace(/\s+/g, "-");
    const fileName = `StockSense-${safeName}-report.pdf`;

    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (err) {
    console.error("PDF generation error:", err);
    return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
  }
}
